// Generated by CoffeeScript 1.4.0
(function() {
  var fs, list;

  fs = require('fs');

  /**
   * @param {Array} paths Path or array of paths to iterate over
   * @param {Object} [config] Configuration object
   * @param {Boolean} [config.recurse=false] Recurse into each directory?
   * @param {RegExp} [config.regex] Match files against a regex?
   * @param {Function} [iterator] Function to run on each file found
   * @return {Array} Files found
  */


  module.exports = list = function() {
    var args, config, iterator, path, paths, results, _ref, _ref1;
    args = Array.prototype.slice.call(arguments);
    paths = args.shift();
    if (!Array.isArray(paths)) {
      paths = [paths];
    }
    config = typeof args[0] === 'object' && Object.keys(args[0]).length ? args.shift() : {};
    if ((_ref = config.recurse) == null) {
      config.recurse = false;
    }
    if ((_ref1 = config.match) == null) {
      config.match = args[0] instanceof RegExp ? args.shift() : null;
    }
    if (typeof args[0] === "function") {
      iterator = args.shift();
    }
    results = [];
    while (path = paths.shift()) {
      fs.readdirSync(path).sort().forEach(function(file) {
        var self, _ref2;
        self = {
          path: path,
          full: "" + path + "/" + file,
          file: file,
          name: (_ref2 = file.match(/^(.+?)(\.\w{2,7})?$/)) != null ? _ref2[1] : void 0
        };
        Object.defineProperty(self, "stat", {
          get: function() {
            return fs.statSync(self.full);
          }
        });
        if (config.recurse && fs.statSync(self.full).isDirectory()) {
          paths.push(self.full);
        }
        if (config.match && !file.match(config.match)) {
          return;
        }
        if (config.type === "file" && !fs.statSync(self.full).isFile() || config.type === "dir" && !fs.statSync(self.full).isDir()) {
          return;
        }
        results.push(self);
        if (iterator) {
          return iterator.call(self, self);
        }
      });
    }
    return results;
  };

}).call(this);
